Repository NOW-SOPT-APP5-KakaoPay/KakaoPay-Android, pull requests merged in 2024-05, with the labels that each got.

#6 [SETTING/#5] 컬러 시스템 추가
  app/src/main/res/values/colors.xml
Labels: ⚙ SETTING, 🌕 문수

#8 [FEAT/#7] 바텀 네비게이션 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/DummyActivity.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/DummyFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/MainActivity.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/all/AllFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/assets/AssetsFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/benefits/BenefitsFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/home/HomeFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/stocks/StocksFragment.kt
  app/src/main/res/drawable/ic_all_black.xml
  app/src/main/res/drawable/ic_assets_black.xml
  app/src/main/res/drawable/ic_benefits_black.xml
  app/src/main/res/drawable/ic_home_black.xml
  app/src/main/res/drawable/ic_stocks_black.xml
  app/src/main/res/drawable/nav_icon_tint.xml
  app/src/main/res/drawable/nav_text_tint.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_all.xml
  app/src/main/res/layout/fragment_assets.xml
  app/src/main/res/layout/fragment_benefits.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_stocks.xml
  app/src/main/res/menu/menu_main_nav.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: ✨ FEAT, 🌕 문수

#14 [FIX/#13] 데이터 바인딩 제거
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/MainActivity.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/all/AllFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/assets/AssetsFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/benefits/BenefitsFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/home/HomeFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/stocks/StocksFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/util/binding/BindingActivity.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/util/binding/BindingBottomSheetFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/util/binding/BindingFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_all.xml
  app/src/main/res/layout/fragment_assets.xml
  app/src/main/res/layout/fragment_benefits.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_stocks.xml
Labels: 🛠️ FIX, 🌕 문수

#15 [FEAT/#11] 송금 UI 구현
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/TransferFragment.kt
  app/src/main/res/drawable/btn_selector_input_number.xml
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_dropdown.xml
  app/src/main/res/drawable/ic_qr_scan.xml
  app/src/main/res/drawable/ic_qr_scan_red.xml
  app/src/main/res/drawable/selector_star.xml
  app/src/main/res/layout/fragment_transfer.xml
  app/src/main/res/layout/item__recent_account.xml
  app/src/main/res/values/colors.xml
Labels: ✨ FEAT, 🌕 문수

#21 [FEAT/#20] 최근송금목록 조회 기능 구현
  app/src/main/java/org/now/sopt/sopt_kakaopay/MemberIdInterceptor.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/RetrofitProvider.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/model/RequestDto.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/model/ResponseDto.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/model/TransactionHistoryDto.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/model/TransactionHistoryResponseDto.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/DummyViewModel.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/TransferFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/transfer/ImageUtil.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/transfer/TransactionHistoryAdapter.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/transfer/TransactionHistoryViewHolder.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/transfer/TransferFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/transfer/TransferViewModel.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/transfer/TransferViewModelFactory.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/service/ApiService.kt
  app/src/main/res/drawable/ic_qr_scan.xml
  app/src/main/res/drawable/ic_star_empty.xml
  app/src/main/res/drawable/ic_star_full.xml
  app/src/main/res/drawable/selector_star.xml
  app/src/main/res/layout/fragment_transfer.xml
  app/src/main/res/layout/item__recent_account.xml
  app/src/main/res/values/themes.xml
Labels: ✨ FEAT, 🌕 문수

#23 [Feat/#10] Home UI 구현
  app/build.gradle
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/home/HomeFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/home/HomeViewPagerAdapter.kt
  app/src/main/res/drawable/bg_bluegrey400_radius_15dp.xml
  app/src/main/res/drawable/bg_bluegrey400_radius_bottom_15dp.xml
  app/src/main/res/drawable/bg_grey200_radius_15dp.xml
  app/src/main/res/drawable/bg_white_radius_15dp.xml
  app/src/main/res/drawable/bg_yellow_radius_15dp.xml
  app/src/main/res/drawable/bg_yellow_radius_bottom_15dp.xml
  app/src/main/res/drawable/bg_yellow_radius_top_15dp.xml
  app/src/main/res/drawable/ic_dot_indicator.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_total_content.xml
  app/src/main/res/values/strings.xml
Labels: ✨ FEAT, 🪁 연진

#31 [REFACTOR/#29] 뷰 연결 및 변경 사항 적용
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/PaymentBottomSheetFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/home/HomeFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/transfer/TransferActivity.kt
  app/src/main/res/layout/activity_transfer.xml
Labels: ♻️ REFACTOR, 🌕 문수

#27 [Feat/#24] 북마크 추가 및 삭제 서버통신
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/now/sopt/sopt_kakaopay/model/BookMarkRequestDto.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/model/BookMarkResponseDto.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/model/TransactionHistoryDto.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/PaymentFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/home/HomeFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/transfer/TransactionHistoryAdapter.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/transfer/TransactionHistoryViewHolder.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/transfer/TransferActivity.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/transfer/TransferViewModel.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/service/ApiService.kt
  app/src/main/res/layout/fragment_transfer.xml
  app/src/main/res/layout/item__recent_account.xml
Labels: ✨ FEAT, 🪁 연진

#33 [REFACTOR/#32] HOME UI - TotalContent 커스텀뷰 적용
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/home/DotsIndicatorDecoration.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/home/DpExtensions.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/home/HomeFragment.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/home/HomeViewPagerAdapter.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/home/SpacingItemDecoration.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/home/TotalContentAdapter.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/home/TotalContentItem.kt
  app/src/main/java/org/now/sopt/sopt_kakaopay/presentation/main/home/TotalContentViewHolder.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/dimens.xml
Labels: ♻️ REFACTOR, 🌕 문수
